app/urls.py
# Create web/urls.py and paste the following
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "web"

urlpatterns = [
    
    path("", views.Index.as_view(), name="index"),
    path("form/", views.Form.as_view(), name="form"),
    path("icon/", views.Icon.as_view(), name="icon"),
    path("buttons/", views.Button.as_view(), name="buttons"),
    path("typography/", views.Typography.as_view(), name="typography"),
    path("charts/", views.Chart.as_view(), name="charts"),
    path("tables/", views.Table.as_view(), name="tables"),
    path("error/", views.Error.as_view(), name="error"),
    
    path("book_create/", views.BookCreate.as_view(), name="book_create"),
    path("book_list/", views.BookList.as_view(), name="book_list"),
    path("book_detail/<str:pk>/", views.BookDetail.as_view(), name="book_detail"),
    path("book_update/<str:pk>/", views.BookUpdate.as_view(), name="book_update"),
    path("book_delete/<str:pk>/", views.BookDelete.as_view(), name="book_delete"),
    path("book_table/", views.BookTable.as_view(), name="book_table"),
    
    path("author_create/", views.AuthorCreate.as_view(), name="author_create"),
    path("author_list/", views.AuthorList.as_view(), name="author_list"),
    path("author_detail/<str:pk>/", views.AuthorDetail.as_view(), name="author_detail"),
    path("author_update/<str:pk>/", views.AuthorUpdate.as_view(), name="author_update"),
    path("author_delete/<str:pk>/", views.AuthorDelete.as_view(), name="author_delete"),
    
    path("user_list/", views.UserList.as_view(), name="user_list"),
    path("user_create/", views.UserCreate.as_view(), name="user_create"),
    path("user_update/<str:pk>/", views.UserUpdate.as_view(), name="user_update"),
    path("user_delete/<str:pk>/", views.UserDelete.as_view(), name="user_delete"),
    

]

ebook/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("app.urls", namespace="app")),
        path('accounts/', include('registration.backends.default.urls')),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "PROJECT Administration"
admin.site.site_title = "PROJECT Admin Portal"
admin.site.index_title = "Welcome to PROJECT Admin Portal"

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy

# Create your models here.

class BookAuthor(models.Model):
    name = models.CharField(max_length=100)
    bio = models.TextField()

    def __str__(self):
        return str(self.name)
    
    def get_absolute_url(self):
        return reverse_lazy('web:author_detail', kwargs={'pk': self.pk})
    
    def get_update_url(self):
        return reverse_lazy('web:author_update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse_lazy('web:author_delete', kwargs={'pk': self.pk})


class Book(models.Model):
    title = models.CharField(max_length=100,help_text="min 20 characters")
    slug = models.SlugField(max_length=100, unique=True)
    year = models.IntegerField()
    author = models.ForeignKey(BookAuthor, on_delete=models.CASCADE, related_name="books")
    cover = models.ImageField("Book Cover",upload_to="covers/", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    is_special = models.BooleanField(default=False)
    is_trending = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.title} ({self.year})"
    
    def get_absolute_url(self):
        return reverse_lazy('web:book_detail', kwargs={'pk': self.pk})
    
    def get_update_url(self):
        return reverse_lazy('web:book_update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse_lazy('web:book_delete', kwargs={'pk': self.pk})
    
    
class FavoriteBook(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    books = models.ManyToManyField(Book)
    
    def __str__(self):
        return str(self.user)

app/views.py
# Edit web/views.py
from typing import Any, Dict
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import json
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from. models import Book,BookAuthor
from django.urls import reverse_lazy
from django.contrib.auth.models import User



class Index(LoginRequiredMixin,TemplateView):
    template_name = "index.html"


class Form(TemplateView):
    template_name = "pages/basic_elements.html"


class Icon(TemplateView):
    template_name = "pages/icon.html"


class Button(TemplateView):
    template_name = "pages/buttons.html"


class Typography(TemplateView):
    template_name = "pages/typography.html"


class Chart(TemplateView):
    template_name = "pages/chartjs.html"


class Table(TemplateView):
    template_name = "pages/tables.html"


class Error(TemplateView):
    template_name = "pages/error-404.html"


# books
class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    template_name = "books/book_create.html"
    fields="__all__"
    # success_url = reverse_lazy('web:book_list',)


class BookList(LoginRequiredMixin, ListView):
    model = Book
    template_name = "books/book_list.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Books"
        return context


class BookDetail(LoginRequiredMixin, DetailView):
    model = Book
    template_name = "books/book_detail.html"


class BookUpdate(LoginRequiredMixin, UpdateView):
    model = Book
    template_name = "books/book_update.html"
    fields = "__all__"


class BookDelete(LoginRequiredMixin, DeleteView):
    model = Book
    template_name = "books/book_delete.html"
    success_url = "/book_list/"


# authors
class AuthorCreate(LoginRequiredMixin,CreateView):
    model=BookAuthor
    template_name="books/author_create.html"
    fields="__all__"
    
    
class AuthorList(LoginRequiredMixin, ListView):
    model = BookAuthor
    template_name = "books/author_list.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Authors"
        return context


class AuthorDetail(LoginRequiredMixin, DetailView):
    model = BookAuthor
    template_name = "books/author_detail.html"


class AuthorUpdate(LoginRequiredMixin, UpdateView):
    model = BookAuthor
    template_name = "books/author_update.html"
    fields = "__all__"


class AuthorDelete(LoginRequiredMixin, DeleteView):
    model = BookAuthor
    template_name = "books/author_delete.html"
    success_url = "/author_list/"


# users
class UserList(LoginRequiredMixin, ListView):
    model = User
    template_name = "users/user_list.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Users"
        return context
    
    
class UserCreate(LoginRequiredMixin,CreateView):
    model=User
    template_name="users/user_create.html"
    fields=("username","email","password")
    success_url=reverse_lazy("web:user_list")
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.save()
        return super().form_valid(form)
    
    
class UserUpdate(LoginRequiredMixin, UpdateView):
    model=User
    template_name="users/user_update.html"
    fields=("username","email","first_name","last_name","is_superuser")
    success_url=reverse_lazy("web:user_list")
    
    
class UserDelete(LoginRequiredMixin, DeleteView):
    model=User
    template_name="users/user_delete.html"
    success_url = reverse_lazy("web:user_list")
    
    
class BookTable(LoginRequiredMixin, ListView):
    model = Book
    template_name = "books/book_table.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Books"
        return context

templates/books/author_list.html
{% extends 'base.html' %}
{% load static i18n crispy_forms_tags %}
{% block content %}

<div class="page-header">
    <h3 class="page-title">
        <a href="{% url 'web:index' %}">
            <span class="page-title-icon bg-gradient-primary text-white mr-2">
                <i class="mdi mdi-home"></i>
            </span> 
        </a> 
        {{title}}
    </h3>
    {% if request.user.is_superuser %}
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            {% if request.user.is_superuser %}
            <li class="breadcrumb-item active" aria-current="page">
                <a href="{% url 'web:author_create' %}" class="btn btn-lg btn-gradient-primary">New {{title}}</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                {% if object_list %}
                <div class="table-responsive">
                    <table class="table table-bordered table-hover border" style="width:100%;">
                        <thead>
                            <tr>
                                <th> # </th>
                                <th> name </th>
                                <th> bio </th>

                                {% if request.user.is_superuser %}<th> Actions </th>{% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in object_list %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td> {{object.name}}</td>
                                <td> {{object.bio}} </td>
                                
                                <td>
                                    <a href="{{object.get_absolute_url}}" class="btn btn-sm btn-circle btn-primary"><i class="mdi mdi-book-open-page-variant"></i></a>
                                    
                                    {% if request.user.is_superuser %}

                                    <a href="{{object.get_update_url}}" class="btn btn-sm btn-circle btn-info"><i class="mdi mdi-pencil"></i></a>
                                    <a href="{{object.get_delete_url}}" class="btn btn-sm btn-circle btn-danger"><i class="mdi mdi-delete"></i></a>
                                    
                                    {% endif %}
                                </td>
                                                               
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

</div>

{% endblock %}

templates/books/book_list.html
{% extends 'base.html' %}
{% load static i18n crispy_forms_tags %}
{% block content %}

<div class="page-header">
    <h3 class="page-title">
       <a href="{% url 'web:index' %}">
            <span class="page-title-icon bg-gradient-primary text-white mr-2">
                <i class="mdi mdi-home"></i>
            </span> 
        </a> 
        {{title}}
    </h3>
    {% if request.user.is_superuser %}
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <a href="{% url 'web:book_create' %}" class="btn btn-lg btn-gradient-primary">New {{title}}</a>
            </li>
        </ul>
    </nav>
    {% endif %}
</div>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                {% if object_list %}
                <div class="table-responsive">
                    <table class="table table-bordered table-hover border" style="width:100%;">
                        <thead>
                            <tr>
                                <th> # </th>
                                <th> name </th>
                                <th> year </th>
                                <th> author </th>price
                                <th> price </th>
                                {% if request.user.is_superuser %}<th> Actions </th>{% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in object_list %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td> {{object.title}}</td>
                                <td> {{object.year}} </td>
                                <td> {{object.author}} </td>
                                <td> {{object.price}} </td>
                                
                                <td>
                                    <a href="{{object.get_absolute_url}}" class="btn btn-sm btn-circle btn-primary"><i class="mdi mdi-book-open-page-variant"></i></a>
                                    
                                    {% if request.user.is_superuser %}

                                    <a href="{{object.get_update_url}}" class="btn btn-sm btn-circle btn-info"><i class="mdi mdi-pencil"></i></a>
                                    <a href="{{object.get_delete_url}}" class="btn btn-sm btn-circle btn-danger"><i class="mdi mdi-delete"></i></a>
                                    
                                    {% endif %}
                                </td>
                                                               
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

</div>

{% endblock %}

templates/books/book_table.html
{% extends 'base.html' %}
{% load static i18n crispy_forms_tags %}
{% block content %}

<div class="page-header">
    <h3 class="page-title">
       <a href="{% url 'web:index' %}">
            <span class="page-title-icon bg-gradient-primary text-white mr-2">
                <i class="mdi mdi-home"></i>
            </span> 
        </a> 
        {{title}}
    </h3>
    {% if request.user.is_superuser %}
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <a href="{% url 'web:book_create' %}" class="btn btn-lg btn-gradient-primary">New {{title}}</a>
            </li>
        </ul>
    </nav>
    {% endif %}
</div>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                {% if object_list %}
                <div class="table-responsive">
                    <table class="table table-bordered table-hover border" style="width:100%;">
                        <thead>
                            <tr>
                                <th> # </th>
                                <th> name </th>
                                <th> year </th>
                                <th> author </th>price
                                <th> price </th>
                                {% if request.user.is_superuser %}<th> Actions </th>{% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in object_list %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td> {{object.title}}</td>
                                <td> {{object.year}} </td>
                                <td> {{object.author}} </td>
                                <td> {{object.price}} </td>
                                
                                <td>
                                    <a href="{{object.get_absolute_url}}" class="btn btn-sm btn-circle btn-primary"><i class="mdi mdi-book-open-page-variant"></i></a>
                                    
                                    {% if request.user.is_superuser %}

                                    <a href="{{object.get_update_url}}" class="btn btn-sm btn-circle btn-info"><i class="mdi mdi-pencil"></i></a>
                                    <a href="{{object.get_delete_url}}" class="btn btn-sm btn-circle btn-danger"><i class="mdi mdi-delete"></i></a>
                                    
                                    {% endif %}
                                </td>
                                                               
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

</div>

{% endblock %}

templates/pages/error-404.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Purple Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End Plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center text-center error-page bg-primary">
          <div class="row flex-grow">
            <div class="col-lg-7 mx-auto text-white">
              <div class="row align-items-center d-flex flex-row">
                <div class="col-lg-6 text-lg-right pr-lg-4">
                  <h1 class="display-1 mb-0">404</h1>
                </div>
                <div class="col-lg-6 error-page-divider text-lg-left pl-lg-4">
                  <h2>SORRY!</h2>
                  <h3 class="font-weight-light">The page you’re looking for was not found.</h3>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-12 text-center mt-xl-2">
                  <a class="text-white font-weight-medium" href="{% url 'web:index' %}">Back to home</a>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-12 mt-xl-2">
                  <p class="text-white font-weight-medium text-center">Copyright &copy; 2021 All rights reserved.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
  </body>
</html>

templates/pages/error-500.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Purple Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End Plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center text-center error-page bg-info">
          <div class="row flex-grow">
            <div class="col-lg-7 mx-auto text-white">
              <div class="row align-items-center d-flex flex-row">
                <div class="col-lg-6 text-lg-right pr-lg-4">
                  <h1 class="display-1 mb-0">500</h1>
                </div>
                <div class="col-lg-6 error-page-divider text-lg-left pl-lg-4">
                  <h2>SORRY!</h2>
                  <h3 class="font-weight-light">Internal server error!</h3>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-12 text-center mt-xl-2">
                  <a class="text-white font-weight-medium" href="{% url 'web:index' %}">Back to home</a>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-12 mt-xl-2">
                  <p class="text-white font-weight-medium text-center">Copyright &copy; 2021 All rights reserved.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <!-- endinject -->
  </body>
</html>

templates/partials/sidebar.html
{% load static %}


<div class="container-fluid page-body-wrapper">
  <nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
      <li class="nav-item nav-profile">
        <a href="#" class="nav-link">
          <div class="nav-profile-image">
            <img src="{% static 'assets/images/faces/face1.jpg' %}" alt="profile">
            <span class="login-status online"></span>
            <!--change to offline or busy as needed-->
          </div>
          <div class="nav-profile-text d-flex flex-column">
            <span class="font-weight-bold mb-2">{{ user.username }}</span>
            <span class="text-secondary text-small">Project Manager</span>
          </div>
          <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'web:index' %}">
          <span class="menu-title">Dashboard</span>
          <i class="mdi mdi-home menu-icon"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
          <span class="menu-title">Basic UI Elements</span>
          <i class="menu-arrow"></i>
          <i class="mdi mdi-crosshairs-gps menu-icon"></i>
        </a>
        <div class="collapse" id="ui-basic">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="{% url 'web:buttons' %}">Buttons</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'web:typography' %}">Typography</a></li>
          </ul>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'web:icon' %}">
          <span class="menu-title">Icons</span>
          <i class="mdi mdi-contacts menu-icon"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'web:form' %}">
          <span class="menu-title">Forms</span>
          <i class="mdi mdi-format-list-bulleted menu-icon"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'web:charts' %}">
          <span class="menu-title">Charts</span>
          <i class="mdi mdi-chart-bar menu-icon"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'web:tables' %}">
          <span class="menu-title">Tables</span>
          <i class="mdi mdi-table-large menu-icon"></i>
        </a>
      </li>
      {% comment %} <li class="nav-item">
        <a class="nav-link" href="{% url 'web:book_create' %}">
          <span class="menu-title">book create</span>
          <i class="mdi mdi-book-plus menu-icon"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'web:author_create' %}">
          <span class="menu-title">author create</span>
          <i class="mdi mdi-account-plus menu-icon"></i>
        </a>
      </li> {% endcomment %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'web:book_list' %}">
          <span class="menu-title">book list</span>
          <i class="mdi mdi-book-open-page-variant menu-icon"></i>
        </a>
      </li>
      </li>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'web:author_list' %}">
          <span class="menu-title">author list</span>
          <i class="mdi mdi-account menu-icon"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'web:user_list' %}">
          <span class="menu-title">user list</span>
          <i class="mdi mdi-account menu-icon"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="collapse" href="#general-pages" aria-expanded="false"
          aria-controls="general-pages">
          <span class="menu-title">Sample Pages</span>
          <i class="menu-arrow"></i>
          <i class="mdi mdi-medical-bag menu-icon"></i>
        </a>
        <div class="collapse" id="general-pages">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="{% url 'auth_login' %}"> Login </a></li>
            <li class="nav-item"> <a class="nav-link" href="pages/samples/register.html"> Register </a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'web:error' %}"> 404 </a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'web:book_create' %}"> book create </a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'web:book_list' %}"> book list </a></li>
          </ul>
        </div>
      </li>
      <li class="nav-item sidebar-actions">
        <span class="nav-link">
          <div class="border-bottom">
            <h6 class="font-weight-normal mb-3">Projects</h6>
          </div>
          <button class="btn btn-block btn-lg btn-gradient-primary mt-4">+ Add a project</button>
          <div class="mt-4">
            <div class="border-bottom">
              <p class="text-secondary">Categories</p>
            </div>
            <ul class="gradient-bullet-list mt-4">
              <li>Free</li>
              <li>Pro</li>
            </ul>
          </div>
        </span>
      </li>
    </ul>
  </nav>

templates/users/user_list.html
{% extends 'base.html' %}
{% load static i18n crispy_forms_tags %}
{% block content %}

<div class="page-header">
    <h3 class="page-title">
       <a href="{% url 'web:index' %}">
            <span class="page-title-icon bg-gradient-primary text-white mr-2">
                <i class="mdi mdi-home"></i>
            </span> 
        </a> 
        {{title}}
    </h3>
    {% if request.user.is_superuser %}
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <a href="{% url 'web:user_create' %}" class="btn btn-lg btn-gradient-primary">New {{title}}</a>
            </li>
        </ul>
    </nav>
    {% endif %}
</div>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                {% if object_list %}
                <div class="table-responsive">
                    <table class="table table-bordered table-hover border" style="width:100%;">
                        <thead>
                            <tr>
                                <th> # </th>
                                <th> username </th>
                                <th> email </th>
                                <th> date join </th>
                                <th> active </th>
                                <th>Superuser</th>
                               
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in object_list %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td> {{object.username}}</td>
                                <td> {{object.email}} </td>
                                <td> {{object.date_joined}} </td>
                                {% if object.is_active %}
                                <td> yes </td>
                                {% else %}
                                <td> no </td>
                                {% endif %}

                                {% if object.is_superuser %}
                                <td> yes </td>
                                {% else %}
                                <td> no </td>
                                {% endif %}
                                
                                
                                
                                <td>

                                    {% if request.user.is_superuser %}

                                    <a href="{% url 'web:user_update' object.id %}" class="btn btn-sm btn-circle btn-info"><i class="mdi mdi-pencil"></i></a>
                                    <a href="{% url 'web:user_delete' object.id %}" class="btn btn-sm btn-circle btn-danger"><i class="mdi mdi-delete"></i></a>
                                    
                                    {% endif %}

                                </td>
                                                               
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

</div>

{% endblock %}